### ISSUE TITLE
Concatenation obfuscates easy length measurement interpretation

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#12]
Given the inputs:

occurrenceRemarks: SOURCE: M.A.CARRIKER JR.
fieldNotes: LENGTH: 117MM. SOFT PARTS COLOR ON LABEL.

the output is lengthinmm:None is_inferred:None standard length type:None

The expected output is lengthinmm:117 is_inferred:0 standard length type "total length"

If you reverse the order of the strings, the length parses correctly. Somehow the concatenation obfuscates the length measurement in this case. The string "LENGTH: 117MM. SOFT PARTS COLOR ON LABEL." alone also parses correctly.

Using a concatenation separator ';   ' rather than just three spaces does make this pattern intelligible.

**Comment by tucotuco** [comment]
Changing the separator to ';   ' rather than three spaces causes no existing tests to fail. Good idea to keep this as a fix to this issue and close when implemented.

**Comment by rafelafrance** [comment]
CSV columns are processed independently now
