### ISSUE TITLE
Pattern Length (L): missed as length indicator

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#13]
Given the string "Meas:Length (L): 5"

the output is lengthinmm:None is_inferred:None standard length type:None

The expected output is lengthinmm:5 is_inferred:1 standard length type:"total length"

The pattern "Length (L):" seems to be missed as a length indicator.

**Comment by tucotuco** [comment]
This pattern parses correctly: "Meas:Total Length (TL): 8.25"

**Comment by rafelafrance** [comment]
Fixed
