### ISSUE TITLE
Trawl data produce false positive length measurements

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#14]
Given the dynamicProperties: {"time collected":"morning", "water depth":"9.1-18.3", "bottom":"rock?", "length":"278" }

the output is lengthinmm:278 is_inferred:1 standard length type: "total length"

The output for this example is an exception, because although the immediate pattern of "length:[n]" fits, the meaning is not an organism measurement. There are many such examples in the data from the UWFC fish collection.

**Comment by rafelafrance** [comment]
I'm matching on text patterns. I would need another field or trait to key off of to fix this.
