### ISSUE TITLE
Spaces in length range pattern confound interpretation

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#15]
For the input string "Total Length: 185 - 252 mm"

the output is lengthinmm:185 is_inferred:1 standard length type: "total length"

The expected output is lengthinmm:None is_inferred:0 standard length type: "total length range"

Apparently the spaces around the '-' confound the interpretation, since the input string "Total Length: 185-252 mm" is parsed correctly.

**Comment by robgur** [comment]
seems like an easy(ish) fix.  Will talk to Rafe about a possible update
heading into Fall...

**Comment by rafelafrance** [comment]
Fixed
