### ISSUE TITLE
UUID can render a false positive length measurement

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#16]
This is entertaining. Given the input string "92a94901-7146-4989-9538-21bfafbc59eb"

the output is lengthinmm:7146 is_inferred:1 standard length type: "total length"

The expected output is lengthinmm:None is_inferred:None standard length type: None

**Comment by robgur** [comment]
Yep this one at least we knew about.  -r

**Comment by rafelafrance** [comment]
We need to:
- [ ] use word breaks around the captures start and end
- [ ]  possibly limit the number of digits for each value
- [ ] Only allow specific abbreviations inside of the notation. I particular the trailing mass units.

**Comment by rafelafrance** [comment]
Fixed by using regular expression look-arounds
