### ISSUE TITLE
North American vs European mammal measurements

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#18]
Both systems use the same notation (e.g., 235-97-31-25=71.9), but signify distinct measures.

In the North American case, the first number is a total length. In the European case, the first number is a head and body length.

Reference: 

https://books.google.fr/books?id=kQEZAAAAQBAJ&pg=PA214&lpg=PA214&dq=total+length+measurement+mammalogy&source=bl&ots=HsbCCrzb7K&sig=PNtzEc11UIh7BGJwkaCbMuDm2YI&hl=en&sa=X&ved=0ahUKEwj28sSIk5LPAhWLDBoKHR3nBwgQ6AEIHjAA#v=onepage&q=total%20length%20measurement%20mammalogy&f=false

**Comment by robgur** [comment]
Ugh. I'd presume that we mostly (totally?) have North American mammalogists
even if the collections come from European localities?  It seems more a
problem for scaling up, where we'd want to check the institution location
and determine what kind of measurement depending on institutional
continent?  I wonder what it is Indian or Asia or Africa?
-r

**Comment by rafelafrance** [comment]
This can be simply handled in the reducers. I will need some indication as to which shorthand notation we are using.

**Comment by rafelafrance** [comment]
Dead issue, closing
