### ISSUE TITLE
Set mark false positive length

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#5]
Given the input string "Misc: 5 of 5 eggs, fresh; 8 up in larch in muskeg; set mark: 661 1-5 64-61"

the output is lengthinmm:661 is_inferred:1

The expected output is lengthinmm:None is_inferred:None as this record shows a set mark (an identifying system for eggs), not a length measurement.

**Comment by robgur** [comment]
That is a tough one, given the syntax of that measurement.  We could look
for "set mark:" and ignore any measurement after that, but I'd suggest we
do this in a later iteration of the extract code.
-r
