### ISSUE TITLE
Pattern with length followed by absence indicator produces false positive

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#7]
Given the input string "tail length in mm: -; total length in mm: -; wing chord in mm: 81.0R; wing spread in mm: -"

the output is lengthinmm:81 is_inferred:1  standard length type "total length"

The expected output is lengthinmm:81 is_inferred:1  standard length type "total length"

The pattern matching is not picking up on the fact the the '-' indicates a missing measurement.

**Comment by robgur** [comment]
Check this again.  I wasn't expecting any output here given the null total
length measurement.

**Comment by tucotuco** [comment]
Right, sorry. 

The expected output is lengthinmm: None is_inferred:0 standard length type: None

**Comment by rafelafrance** [comment]
Fixed
