### ISSUE TITLE
Fractional english units give incorrect length

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#8]
Given the input string "LENGTH 10 3/8 IN. WING CHORD 5.25 IN. TAIL 4.25 IN."

the output is lengthinmm:10 is_inferred:1 standard length type: "total length"

The expected output is lengthinmm:263.5 is_inferred:0 standard length type: "total length"

There is no pattern detection for fractional english units.

**Comment by rafelafrance** [comment]
Fixed
