### ISSUE TITLE
Incorrect units when units separated from value by another measurement

### ISSUE THREAD

**Issue by tucotuco** [rafelafrance/traiter#9]
Given the input string "SV 1.4, TAIL 1.0 CM. HATCHLING"

the output is lengthinmm:1.4 is_inferred:1 standard length type: "snout-vent length"

The expected output is lengthinmm:14 is_inferred:0 standard length type: "snout-vent length"

The pattern of having the unit separated from the value in this way seems not to be covered.

**Comment by robgur** [comment]
I disagree with this one.  I think there is no evidence as to units for
this one, despite the tail units.

**Comment by tucotuco** [comment]
I sincerely doubt the SV could be 1.4mm on a vertebrate, especially with a tail of 1cm.

**Comment by robgur** [comment]
Ok good point - that is a strong inference! :)

**Comment by rafelafrance** [comment]
It may be possible to pick this up in the new post processing step.

**Comment by rafelafrance** [comment]
Dead issue closing
